### ISSUE TITLE
is there a converter between PHH and major sites' hand history formats?

### ISSUE THREAD

**Issue by carlguo866** [uoftcprg/phh-std#1]
Title. More practically, I'm looking for a way to convert my hands so they can be uploaded to GTO Wizard through one of their supported formats.

**Comment by AussieSeaweed** [comment]
Sorry for the late response. The latest developmental version of [PokerKit](https://github.com/uoftcprg/pokerkit) has various third-party formats-to-PHH converter implementations. It is not yet published yet.
